#!/bin/bash
set -u

LOG="$HOME/anonymous_smoke_test_$(date +%F_%H%M%S).log"
REPO_DIR="$HOME/test_repo"
PY="/opt/alt/python311/bin/python3"
VENV_DIR="$REPO_DIR/.venv311_test"

ok=1
reason=""
action=""

say(){ echo "$*" | tee -a "$LOG"; }

say "=== ANONYMOUS SMOKE TEST (0/1) ==="
say "DATE: $(date)"
say "REPO_DIR: $REPO_DIR"
say "PY: $PY"
say ""

# --- Preflight ---
say "1) Preflight checks..."
if [ ! -d "$REPO_DIR" ]; then ok=0; reason="Repo directory not found: $REPO_DIR"; action="Clone repo first"; fi
if [ "$ok" -eq 1 ] && [ ! -x "$PY" ]; then ok=0; reason="Python 3.11 not found at $PY"; action="Hosting support must enable 
/opt/alt/python311"; fi
if [ "$ok" -eq 1 ] && [ ! -f "$REPO_DIR/requirements.txt" ]; then ok=0; reason="requirements.txt missing"; action="Fix repo structure"; 
fi
say "Preflight: $( [ "$ok" -eq 1 ] && echo PASS || echo FAIL )"
say ""

# --- Clean venv ---
if [ "$ok" -eq 1 ]; then
  say "2) Cleaning old test venv..."
  rm -rf "$VENV_DIR" 2>/dev/null || true
  say "OK"
  say ""
fi

# --- Create venv ---
if [ "$ok" -eq 1 ]; then
  say "3) Creating venv (3.11)..."
  "$PY" -m venv "$VENV_DIR" >>"$LOG" 2>&1 || { ok=0; reason="venv creation failed"; action="Support (python/venv broken)"; }
  say "$( [ "$ok" -eq 1 ] && echo PASS || echo FAIL )"
  say ""
fi

# --- Install deps ---
if [ "$ok" -eq 1 ]; then
  say "4) Installing dependencies..."
  source "$VENV_DIR/bin/activate"
  python -m pip install --upgrade pip setuptools wheel >>"$LOG" 2>&1 || { ok=0; reason="pip upgrade failed"; action="Check outbound/SSL, 
hosting policy"; }
  python -m pip install -r "$REPO_DIR/requirements.txt" >>"$LOG" 2>&1 || { ok=0; reason="requirements install failed"; action="Fix 
requirements or missing wheels/system deps"; }
  say "$( [ "$ok" -eq 1 ] && echo PASS || echo FAIL )"
  say ""
fi

# --- Discover entrypoint heuristics ---
APP_IMPORT_CANDIDATES=(
  "app"
  "app.app"
  "app.main"
  "app.wsgi"
  "app.__init__"
)

# --- Import test ---
if [ "$ok" -eq 1 ]; then
  say "5) Import test (find a working module)..."
  FOUND=""
  for m in "${APP_IMPORT_CANDIDATES[@]}"; do
    python - <<PY >>"$LOG" 2>&1
import importlib
import sys
m="${m}"
try:
    importlib.import_module(m)
    print("IMPORT_OK", m)
except Exception as e:
    print("IMPORT_FAIL", m, type(e).__name__, str(e)[:200])
    sys.exit(1)
PY
    if grep -q "IMPORT_OK ${m}" "$LOG"; then
      FOUND="$m"
      break
    fi
  done

  if [ -z "$FOUND" ]; then
    ok=0
    reason="Could not import any candidate module under app/"
    action="Need correct entry module name; check run_local.sh / app package"
    say "FAIL"
  else
    say "PASS: import works for module: $FOUND"
  fi
  say ""
fi

# --- WSGI stub creation test (Passenger expects passenger_wsgi.py) ---
# This does NOT guarantee Passenger is configured, but guarantees we can build a WSGI entry file.
if [ "$ok" -eq 1 ]; then
  say "6) Create minimal passenger_wsgi.py (best-effort) ..."
  WSGI_FILE="$REPO_DIR/passenger_wsgi.py"
  cat > "$WSGI_FILE" <<'WSGI'
"""
Passenger WSGI entrypoint (generated by smoke test).
You may need to adjust import below to match your framework.
"""
import os
import sys

# Ensure project root on path
BASE_DIR = os.path.dirname(__file__)
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

# TODO: Adjust these imports once confirmed:
# - Flask: expose 'application' as WSGI callable
# - FastAPI: needs ASGI->WSGI adapter (usually not supported directly by Passenger)
try:
    from app import app as application  # common Flask pattern
except Exception:
    # fallback: try app.app
    from app.app import app as application
WSGI
  say "PASS: passenger_wsgi.py created at $WSGI_FILE"
  say ""
fi

# --- Basic "can we run python file" test ---
if [ "$ok" -eq 1 ]; then
  say "7) Sanity run passenger_wsgi import..."
  python -c "import passenger_wsgi; print('WSGI_IMPORT_OK')" >>"$LOG" 2>&1 || {
    ok=0
    reason="passenger_wsgi.py import failed (entrypoint mismatch)"
    action="Adjust passenger_wsgi.py imports to your actual app object; likely user-fixable"
  }
  say "$( [ "$ok" -eq 1 ] && echo PASS || echo FAIL )"
  say ""
fi

# --- Cleanup venv (optional) ---
if [ "$ok" -eq 1 ]; then
  say "8) Cleanup test venv (optional)..."
  deactivate 2>/dev/null || true
  rm -rf "$VENV_DIR" 2>/dev/null || true
  say "OK"
  say ""
fi

say "=============================="
if [ "$ok" -eq 1 ]; then
  say "FINAL RESULT: OK"
  say "Anonymous should be deployable here (Python 3.11 + deps OK)."
  say "Next step: configure cPanel 'Setup Python App' to point to this repo and passenger_wsgi.py."
else
  say "FINAL RESULT: NOT OK"
  say "Reason: $reason"
  say "Action: $action"
  say "Tip: share log: $LOG"
fi
say "=============================="
